apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: welcomer
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: welcomer
      revisionHistoryLimit: 5
      progressDeadlineSeconds: 300
      minReadySeconds: 10
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 1
          maxSurge: 1
      template:
        metadata:
          labels:
            app: welcomer
        spec:
          containers:
            - name: funnybizz-app
              image: alekslitvinenk/welcomer:v0.2.4
              imagePullPolicy: Always
              ports:
                - name: nodejs
                  containerPort: 3000
                  protocol: TCP
              env:
                - name: DB_USER
                  value: root
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: mariadb-creds
                      key: mariadb_root_password
                      optional: false
                - name: DB_HOST
                  value: mariadb-svc
                - name: DB_SCHEMA
                  value: telegram
  - apiVersion: v1
    kind: Service
    metadata:
      name: welcomer-svc
      annotations:
        service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
      labels:
        app: welcomer
    spec:
      type: ClusterIP
      ports:
        - port: 3000
          name: nodejs
          protocol: TCP
      selector:
        app: welcomer